psu-img: Update AEI firmware files
ibm-openbmc/device-images pull request #4
Opened 2024-11-22 15:31 UTC by faisal-awada

Removing the old firmware files 51E9.hex and 51DA.hex, which are in Motorola HEX format, and replacing them with the Intel HEX format files 51E9.bin and 51DA.bin. The BIN files contain the latest firmware versions. Additionaly, update the MANIFEST file to reflect the new firmware versions.

Change-Id: If352bc3a27f0eedcb6218cc9a1f13348e791cc84

2024-11-22 16:14 UTC, derekhoward55 requested changes
In the commit message it's stated "Removing the old firmware files 51E9.hex and 51DA.hex, which are in Motorola HEX format, and replacing them with the Intel HEX format files 51E9.bin and 51DA.bin."

However the .bin files are not intel hex format files.  I'd word it something like "Removing the old firmware files 51E9.hex and 51DA.hex, which are in HEX format, and replacing them with the binary files 51E9.bin and 51DA.bin." to avoid confusion.

2024-11-22 17:16 UTC, smccarney commented
@faisal-awada Based on a little google searching it appears to me that:
* Intel HEX format is ASCII and is the format of the current files in device-images
* Motorola S-Record is another ASCII format and is not involved here
* Binary format is what the new files are using

If this is true, can you update the commit message and the PR description to say we are moving from Intel HEX format to binary format?

2024-11-22 17:17 UTC, smccarney commented
@faisal-awada I believe you said there is a way to obtain the version within the binary file by looking at a certain offset.

Did you confirm that the version within the binary file matched the version you put in the MANIFEST file?

2024-11-25 20:52 UTC, smccarney reviewed
Other than my previous two comments, this PR looks good to me.

2024-11-26 19:56 UTC, faisal-awada commented
> @faisal-awada I believe you said there is a way to obtain the version within the binary file by looking at a certain offset.
> 
> Did you confirm that the version within the binary file matched the version you put in the MANIFEST file?

@smccarney Downloaded the firmware to PSU then used psutils to get current version which I placed in the MANIFEST file

2024-11-26 23:55 UTC, derekhoward55 approved these changes

2025-01-22 22:16 UTC, closed without merging